apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ccjgnwwe9-nodejs 
  janus-idp.io/tekton: ccjgnwwe9-nodejs
  backstage.io/kubernetes-id: ccjgnwwe9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccjgnwwe9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml